### ISSUE TITLE
[Suggestion] Add different invasions with various mobs. (like from Terraria!)

### ISSUE THREAD

**Issue by Fenlas** [Calculus-Master/DifficultRaids#1]
If it's not beyond the scope of this mod. You should add mob invasions! Where upon a certain day (or upon getting the Bad Omen debuff) an group of mobs invade your location.

The invasion will occur around your home, and attack just like the illagers. Though the set of invaders could be:
- An Undead wave of zombies and skeletons. 
- An creeper fest of pain and suffering.
- An piglin invasion, because they want your gold.
- Maybe a custom invasion featuring mod support?

Dunno, this could just be too complicated with the raid mechanics. Figured I'd throw this out there.

**Comment by Calculus-Master** [comment]
That sounds pretty interesting! I do think it may be a bit out of the scope of this mod specifically, but I can totally look into making a separate mod that focuses on that.
