### ISSUE TITLE
want only vanilla illagers

### ISSUE THREAD

**Issue by zetagi21** [Calculus-Master/DifficultRaids#12]
I only want vanilla illagers to spawn and not modded ones, can there be an option in the config to include that?

**Comment by Calculus-Master** [comment]
You can toggle individual raider types in the general.toml config file.

**Comment by zetagi21** [comment]
theres no config in the new 1.19.2 version

**Comment by zetagi21** [comment]
oh wait its in server config thanks

**Comment by Calculus-Master** [comment]
Yeah sure np! That's actually going to be changing in the next 1.19.2 version, I rewrote the config and one of the changes is that it's going to become a common config, so it'll be in the regular config folder rather than serverconfig.

**Comment by zetagi21** [comment]
how do i prevent bosses from spawning?

**Comment by Calculus-Master** [comment]
There's a config option called "elitesEnabled" in each raid difficulty config, turning that off will make them not spawn in that difficulty.

**Comment by zetagi21** [comment]
thank you so much! also one more suggestion, i would like raids to be more configurable, like  for example how many waves or how many enemies spawn each raid

**Comment by Calculus-Master** [comment]
Thanks for the suggestion!
That's actually something I've been looking into! Configuring the number of raiders per wave should be coming soon, changing the number of waves (in a way that makes them configurable) may be a little more challenging but it's something I'll look into.

**Comment by Calculus-Master** [comment]
This has been added in v2.0.beta.7
