### ISSUE TITLE
Game Crash on Raid Wave Start Version 1.19.2

### ISSUE THREAD

**Issue by DoctorofBadMedicine** [Calculus-Master/DifficultRaids#13]
Game will crash when a raid wave begins and gives the error message, 

The game crashed whilst exception ticking world
Error: java.lang.NullPointerException: Cannot invoke "com.calculusmaster.difficultraids.data.RaidEnemyManager.isEliteWave(int)" because the return value of "java.util.Map.get(Object)" is null

mods that I have installed are
- Difficult Raids [FORGE]
- Just Enough Items (JEI)
- Mouse Tweaks

This may have been caused by the fact that I may be missing a dependency mod of some sort and if that's the case, sorry!

**Comment by Calculus-Master** [comment]
I don't believe it's due to a missing dependency (DR doesn't have any hard dependencies)
Were you trying to start a raid with bad omen level 1?

**Comment by Calculus-Master** [comment]
Fixed it in another report #14 – thanks for yours as well! Version 2.0-beta.9.1 has the fix on CurseForge.
