### ISSUE TITLE
latest version crash the game 

### ISSUE THREAD

**Issue by littlepianist** [Calculus-Master/DifficultRaids#2]
[crash-2022-05-05_21.36.19-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/8637071/crash-2022-05-05_21.36.19-server.txt)

**Comment by Calculus-Master** [comment]
Thanks, I'll look into it. What Raid Difficulty were you on?

**Comment by Calculus-Master** [comment]
Also, what was your mod list?

**Comment by littlepianist** [comment]
I don't really remember, but I use the mod with illagers wear armor. I will try the updated version and see if it still crashes.
