### ISSUE TITLE
Exception ticking world on Default wave

### ISSUE THREAD

**Issue by KingKottlewing** [Calculus-Master/DifficultRaids#21]
[2024-04-11-4.log](https://github.com/Calculus-Master/DifficultRaids/files/14961856/2024-04-11-4.log)
[crash-2024-04-11_20.07.08-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/14961857/crash-2024-04-11_20.07.08-server.txt)
[crash-2024-04-22_21.32.23-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/15067982/crash-2024-04-22_21.32.23-server.txt)

Unsure if I'll get support here since the server is hybrid, but it seems to have happened before, looking at previous issues.
Don't think I made an error in the config since I did the exact same for other raid levels but here it is anyways - https://pastebin.com/6vDbuwAA

**Comment by KingKottlewing** [comment]
[crash-2024-05-18_00.51.02-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/15358739/crash-2024-05-18_00.51.02-server.txt)
[crash-2024-05-18_00.58.51-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/15358740/crash-2024-05-18_00.58.51-server.txt)
Few more reports, config is still the same

**Comment by Calculus-Master** [comment]
Hey, thanks for the report! I'm just getting back into working on the mod so I can take a look at fixing this soon.

**Comment by Calculus-Master** [comment]
I've fixed this, thanks again for providing the crash reports! It'll be in the next 1.18 version (1.7.6) which should be out in the next few days.
