### ISSUE TITLE
without guard villager mod, I can't enter any save.

### ISSUE THREAD

**Issue by rtxyd** [Calculus-Master/DifficultRaids#3]
version: difficultraids-1.3-beta, 
case: entering any new/old save always show datapack issue, I see debug.txt and it shows missing gurad villager mod, so I add it, then I can enter saves, but there is a bug in guard villager mod which you can duplicate your items and enchant them for free, so I don't want to add it.

**Comment by Calculus-Master** [comment]
Can you send me a log where you enter a save without the mod vs when you enter with the mod?

**Comment by Jukabofy** [comment]
CAn confirm

**Comment by Calculus-Master** [comment]
I believe I've fixed this (v1.1.3), let me know if the issue still persists.

**Comment by Jukabofy** [comment]
Yeaa, it works properly now
