### ISSUE TITLE
Difficult Raid illagers are not in the #minecraft:raiders tag

### ISSUE THREAD

**Issue by Yellowbross** [Calculus-Master/DifficultRaids#4]
illagers from this mod are not in the "minecraft:raiders" tag. while this isn't that big of a problem, it makes things like raid battles much more frustratingly tedious since you can't just use one-commands like "/tp @e[type=#raiders] ~ ~ ~"

to reproduce:
1. summon any illager from Difficult Raids, alongside a pillager
2. run the command "/kill @e[type=#raiders]"
3. the difficult raids illager isn't affected by the command, but the pillager is

**Comment by KaratFeng** [comment]
I'd like to stress this as important to fix, having to add a command block to every type of illager is a waste of time, when it could be done with the tag

**Comment by Calculus-Master** [comment]
Thanks for letting me know, this has been fixed in v1.6.1
