### ISSUE TITLE
Grandmaster Raid Crash 

### ISSUE THREAD

**Issue by CombatSwift** [Calculus-Master/DifficultRaids#5]
Our server has this mod installed for 1.18.2, for whatever reason during the most difficult raid (grandmaster raid) It crashes with "ticking entity" then it reboots but crashes again with "Watching server" after that it reboots again and works fine
[crash-2022-07-31_03.34.10-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/9245623/crash-2022-07-31_03.34.10-server.txt)
[crash-2022-07-31_03.33.06-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/9245624/crash-2022-07-31_03.33.06-server.txt)

**Comment by CombatSwift** [comment]
Misleading title sorry! I am hosting this server for my friends and they just confirmed it's happening OUTSIDE of GRANDMASTER raids as well. 

I am thinking it might be the necromancer causing it?

**Comment by Calculus-Master** [comment]
Ah, a temporary fix you guys can use is to go into server.properties and set the max-tick-time property to -1, which disables the server watchdog.
I'll look into the Necromancer and see if anything's being a heavy load on the TPS - any reason why you think it might be that mob by the way? Just so I can pinpoint any issues.

Additionally, this is somewhat common for large modpacks so it could be a result of any mods you've got on the server.

**Comment by CombatSwift** [comment]
Ok, I have figured out which mob is exactly doing it, it is not the necromancer. It is the Xydrax Boss. He even crashes singleplayer worlds.

**Comment by CombatSwift** [comment]
I attempted spawning him in both the server and in singleplayer, both resulted in immediate crashes.

**Comment by CombatSwift** [comment]
Modur and Voldon work can be spawned normally. (unable to test Nuaos as when I attempt to summon him all I get is "An unexpected error occurred trying to exeute that command") When Xydrax is summon though he crashes the game.

**Comment by Calculus-Master** [comment]
Alright, can you send me a crash report after you try summoning it? The mobs aren't supposed to be summoned outside of Raids since they're tied directly to them, so I may end up just altering the message to alert players.

**Comment by CombatSwift** [comment]
[crash-2022-08-02_21.41.26-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/9246037/crash-2022-08-02_21.41.26-server.txt)
[crash-2022-08-02_21.40.24-server.txt](https://github.com/Calculus-Master/DifficultRaids/files/9246038/crash-2022-08-02_21.40.24-server.txt)

**Comment by CombatSwift** [comment]
So do you  think this would still fix the issue? 

"server.properties and set the max-tick-time property to -1, which disables the server watchdog."

**Comment by Calculus-Master** [comment]
Yeah that'll fix the watchdog crash, but the summoning thing I'll work on fixing (which is the 2nd crash report you sent).

**Comment by CombatSwift** [comment]
Thank you!

**Comment by Calculus-Master** [comment]
The issue has been fixed in v1.6.2.
