### ISSUE TITLE
Crash During Raid

### ISSUE THREAD

**Issue by Smartin-b** [Calculus-Master/DifficultRaids#6]
[2022-08-06-1.log.gz](https://github.com/Calculus-Master/DifficultRaids/files/9275777/2022-08-06-1.log.gz)
Crash, seems to be caused by improper compat code for Guardvilligers
Happened during a T3 Raid(legen) in i think wave 4

**Comment by Calculus-Master** [comment]
Thanks for the report, it seems to be the same issue as #5 . 
I'll get a fix out soon.

**Comment by Smartin-b** [comment]
u can see a blue bossbar, the boss isnt there after a serverrestart

**Comment by Calculus-Master** [comment]
The crash has been fixed in v1.6.2. I'll look into the blue boss bar disappearing after reloading the world.
