### ISSUE TITLE
Nuaos can't be /summoned

### ISSUE THREAD

**Issue by Yellowbross** [Calculus-Master/DifficultRaids#7]
trying to use /summon to spawn nuaos will result in the chat saying "An unexpected error occurred trying to execute that command"

to reproduce:
1. run the command "/summon difficultraids:nuaos_elite"
2. the game fails to summon nuaos

by the way: spawn eggs for each illager would be nice, considering you have to use /summon to spawn them

**Comment by Calculus-Master** [comment]
Is this during a Raid or outside? And can you send a log after you try to /summon? Thanks

**Comment by Yellowbross** [comment]
using /summon seems the log doesn't show anything, but:
i managed to get nuaos to spawn during a legend raid, and using the mob battle mod to try and spawn nuaos with the mob spawn egg i managed to achieve a log error to why nuaos can't be spawned!
[debug.log](https://github.com/Calculus-Master/DifficultRaids/files/9293570/debug.log)

**Comment by Calculus-Master** [comment]
Alright, thank you so much, that helps a lot! I'll fix it soon.

**Comment by Calculus-Master** [comment]
This is fixed in the latest release (1.7).
