### ISSUE TITLE
Voldon bug...? (1.18.2)

### ISSUE THREAD

**Issue by zoke1903** [Calculus-Master/DifficultRaids#8]
Voldon's fireball always goes up in the sky. Is this normal?
Even the fireball remains intact.

![2022-10-28_02 03 27](https://user-images.githubusercontent.com/116832796/198353792-7695efae-f973-44b0-9f75-e710db501858.png)
![2022-10-28_02 03 33](https://user-images.githubusercontent.com/116832796/198353801-1761e504-b646-40f6-8e70-8dd1a394d5b6.png)
![2022-10-28_02 03 25](https://user-images.githubusercontent.com/116832796/198353781-eb762b08-db6d-4d9f-b74b-6b826aa84995.png)

**Comment by Calculus-Master** [comment]
That's definitely not normal, and I was having issues with its fireball attack in general so I'll look into it.
What difficulty raid was it? And what was your Minecraft difficulty? (Easy, Normal, Hard)

**Comment by zoke1903** [comment]
The difficulty level of Minecraft was hard.
(Hardcore X, 어려움 = hard)
![2022-10-28_15 57 57](https://user-images.githubusercontent.com/116832796/198523473-9d8487a9-8ef5-411f-aec3-330ce119b38c.png)

**Comment by Calculus-Master** [comment]
I've pushed this in 1.7.1 - I've removed the attack for now (it was temporary anyways), and will add a more unique one for the 1.19 version.
