### ISSUE TITLE
Nuaos doesn't change texture when taking damage

### ISSUE THREAD

**Issue by ZestyBlaze** [Calculus-Master/DifficultRaids#9]
I spotted when going through the code that there is the idea that Nuaos will look "angrier" as he stores damage before releasing it but through testing, it seems like he doesn't actually change textures

Also, hi! I'm the person on Curseforge who asked about making a Fabric port of this mod and I'm 95% done with making a port! If there is anything you'd like to chat to me about, feel free to add me on Discord (ZestyBlaze#4208)

**Comment by Calculus-Master** [comment]
Yeah I noticed that as well, I was looking into it. The method I was using for changed textures works perfectly for the Voldon Familiars, so I'm unsure why Nuaos isn't - I'll do some more debugging when I have some free time though!

**Comment by ZestyBlaze** [comment]
Also hi I'm the person who commented on the CF page about a Fabric port, I've finished it and before I release it or do something with it, I'd just like to check and make sure you are okay with the mod being released and ask you what share of the points you would like :)

**Comment by Calculus-Master** [comment]
Fixed in the 1.19 version (in dev).
